# Civil 3D MCP — Interactive Setup
# Detects installed Civil 3D versions, configures plugin references, and builds.

param(
    [string]$AutoSelectYear,
    [switch]$SkipNpm,
    [switch]$SkipPlugin
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$PluginDir = Join-Path $RepoRoot "plugin\Civil3dMcpPlugin"
$PropsFile = Join-Path $PluginDir "Civil3dMcpPlugin.References.props"

function Write-Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "  [!!] $msg" -ForegroundColor Yellow }

function Get-TargetFramework($year) {
    switch ([int]$year) {
        { $_ -ge 2027 } { return "net10.0-windows" }
        { $_ -ge 2026 } { return "net9.0-windows" }
        default         { return "net8.0-windows" }
    }
}

function Find-Civil3DInstalls {
    $base = "C:\Program Files\Autodesk"
    if (-not (Test-Path $base)) { return @() }

    $installs = @()
    Get-ChildItem -Path $base -Directory -Filter "AutoCAD *" | ForEach-Object {
        $year = ($_.Name -replace "AutoCAD ", "").Trim()
        $c3dDll = Join-Path $_.FullName "C3D\AeccDbMgd.dll"
        if (Test-Path $c3dDll) {
            $installs += [PSCustomObject]@{
                Year = $year
                Path = $_.FullName
                Framework = Get-TargetFramework $year
            }
        }
    }
    return $installs | Sort-Object { [int]$_.Year } -Descending
}

function Write-PropsFile($install) {
    $content = @"
<Project>
  <!-- Generated by scripts/setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm") -->
  <PropertyGroup>
    <AutoCADInstallPath>$($install.Path)</AutoCADInstallPath>
    <Civil3dTargetFramework>$($install.Framework)</Civil3dTargetFramework>
    <AutoCADYear>$($install.Year)</AutoCADYear>
  </PropertyGroup>
</Project>
"@
    Set-Content -Path $PropsFile -Value $content -Encoding UTF8
    Write-Ok "Wrote $PropsFile"
}

function Show-McpConfig($dllPath) {
    $mcpPath = (Join-Path $RepoRoot "build\index.js") -replace "\\", "/"
    Write-Step "MCP Configuration (add to Cursor mcp.json)"
    Write-Host @"
{
  "mcpServers": {
    "civil3d": {
      "command": "node",
      "args": ["$mcpPath"],
      "env": {
        "CIVIL3D_PORT": "8080"
      }
    }
  }
}
"@
    Write-Step "Civil 3D Plugin"
    Write-Host "  NETLOAD -> $dllPath"
    Write-Host "  C3DMCPSTATUS -> verify listener"
}

# ── Main ──

Write-Host ""
Write-Host "  Civil 3D MCP Setup" -ForegroundColor White -BackgroundColor DarkBlue
Write-Host ""

Write-Step "Scanning for Civil 3D installations..."
$installs = Find-Civil3DInstalls

if ($installs.Count -eq 0) {
    Write-Warn "No Civil 3D installations found under C:\Program Files\Autodesk\AutoCAD *"
    Write-Warn "Install Civil 3D or check the installation path."
    exit 1
}

Write-Ok "Found $($installs.Count) installation(s):"
for ($i = 0; $i -lt $installs.Count; $i++) {
    $inst = $installs[$i]
    Write-Host "  [$($i + 1)] Civil 3D $($inst.Year)  ($($inst.Framework))  $($inst.Path)"
}

$selected = $null
if ($AutoSelectYear) {
    $selected = $installs | Where-Object { $_.Year -eq $AutoSelectYear } | Select-Object -First 1
    if (-not $selected) {
        Write-Warn "Year $AutoSelectYear not found. Using newest."
        $selected = $installs[0]
    }
} else {
  Write-Host ""
  $choice = Read-Host "Select version [1-$($installs.Count)] (default: 1 = newest)"
  if ([string]::IsNullOrWhiteSpace($choice)) { $choice = "1" }
  $index = [int]$choice - 1
  if ($index -lt 0 -or $index -ge $installs.Count) {
      Write-Warn "Invalid choice. Using newest."
      $index = 0
  }
  $selected = $installs[$index]
}

Write-Ok "Selected: Civil 3D $($selected.Year)"
Write-Step "Configuring plugin references..."
Write-PropsFile $selected

if (-not $SkipNpm) {
    Write-Step "Building MCP server (npm)..."
    Push-Location $RepoRoot
    npm install
    npm run build
    Pop-Location
    Write-Ok "MCP server built"
}

if (-not $SkipPlugin) {
    Write-Step "Building Civil 3D plugin (dotnet)..."
    Push-Location $PluginDir
    dotnet build -c Release
    Pop-Location
    $dll = Join-Path $PluginDir "bin\Release\$($selected.Framework)\Civil3dMcpPlugin.dll"
    if (-not (Test-Path $dll)) {
        $dll = Join-Path $PluginDir "bin\Debug\$($selected.Framework)\Civil3dMcpPlugin.dll"
    }
    Write-Ok "Plugin built: $dll"
    Show-McpConfig $dll
} else {
    Show-McpConfig "(run dotnet build to get DLL path)"
}

Write-Host ""
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host ""
